Make UI for the screen of creating a note
alexnikxx/Notes pull request #4
Opened 2024-03-17 18:27 UTC by alexnikxx

2024-03-17 19:16 UTC, yukim17 requested changes

2024-03-17 19:16 UTC, yukim17 commented on Notes/CheckboxView.swift
> +class CheckboxView: UIView {
Советую всегда делать класс final, если ты сразу знаешь что от него потом не будет наследников

2024-03-17 19:16 UTC, yukim17 commented on Notes/CheckboxView.swift
> +    var shapePosition: CGPoint = .zero
Тут я не совсем поняла, ты изначально планировала менять позицию и размер фигуры извне или все-таки это должны быть private проперти?

2024-03-17 19:16 UTC, yukim17 commented on Notes/CheckboxView.swift
> +        super.draw(rect)
На самом деле не обязательно вызывать super.draw(rect). Потому что функция draw у UIView ничего не делает, да-да совсем ничего. Об этом даже в документации написано. То есть если не вызовешь super.draw(rect) ничего не сломается

2024-03-17 19:16 UTC, yukim17 commented on Notes/CheckboxView.swift
> +    private func getCheckboxPath(in rect: CGRect) -> UIBezierPath {
Молодец, не забыла тут про private!

2024-03-17 19:16 UTC, yukim17 commented on Notes/CheckboxView.swift
> +        let circle = UIBezierPath(arcCenter: CGPoint(x: halfSize, y: halfSize),
Когда много параметров у функции, лучше переносить их на новую строку в таком формате:
```
let circle = UIBezierPath(
        arcCenter: CGPoint(x: halfSize, y: halfSize),
        radius: CGFloat(halfSize - (desiredLineWidth / 2)),
        startAngle: CGFloat(0),
        endAngle: CGFloat(CGFloat.pi * 2),
        clockwise: true
)
```
Обычно так намного лучше читается и в коде, и при код ревью

2024-03-17 19:16 UTC, yukim17 commented on Notes/ViewController2.swift
> +class ViewController2: UIViewController {
Тоже final

2024-03-17 19:16 UTC, yukim17 commented on Notes/ViewController2.swift
> +    var checkbox = CheckboxView()
Модификатор доступа стоит добавить

2024-03-17 19:16 UTC, yukim17 commented on Notes/ViewController2.swift
> +
Лишние переносы строки тож не стоит добавлять, если хочешь логически отделить части класса друг от друга добавляй марки с комментариями, например:
```
// MARK: - Properties
// MARK: - Lifecycle
// MARK: - Private methods
```

2024-03-17 19:16 UTC, yukim17 commented on Notes/ViewController2.swift
> +        firstColor.layer.borderWidth = 1.5
Смотри у тебя тут куча повторяющегося кода - можно подумать как это дело сократить. Можно создать отдельную функцию под это, но на функция на две строчки кажется слишком. Можно сделать например вот так:
```
let colorViews = [firstColor, secondColor, thirdColor, forthColor]
colorView.forEach { color in
     color.layer.borderWidth = 1.5
     color.layer.borderColor = UIColor.black.cgColor
}
```
Сразу код стал лаконичнее

2024-03-17 19:16 UTC, yukim17 commented on Notes/ViewController2.swift
> +        checkbox.frame.size.height = 28
Какой-то финт ушами получился. Ты сначала присваиваешь высоту и ширину фрейму, а потом тупо весь фрейм меняешь. Возникает вопрос зачем тогда первое действие делать, если когда ты фрейм меняешь твоя высота и ширина перезаписывается? Сделай просто переменные отдельно с высотой и шириной и потом уже в фрейм их положи

2024-03-17 19:16 UTC, yukim17 commented on Notes/ViewController2.swift
> +        let newXPosition = checkbox.frame.origin.x + 36
Тут не совсем ясно зачем используешь checkbox.frame.origin.x. Изначально у любой вьюзи позиуия 0,0, вью дид лоад вызывается только один раз за всю работу вью контроллера, то есть позиция точно не будет отличная от 0, 0. Поэтому выглядит излишне

2024-04-02 20:16 UTC, alexnikxx commented on Notes/CheckboxView.swift
> +    private func getCheckboxPath(in rect: CGRect) -> UIBezierPath {
Думаю, это потому, что в видео было

2024-04-02 20:20 UTC, alexnikxx commented on Notes/ViewController2.swift
> +
случайно оставила, буду следить

2024-04-02 20:22 UTC, alexnikxx commented on Notes/ViewController2.swift
> +        firstColor.layer.borderWidth = 1.5
Почему-то он делает colorViews массивом опциональных вьюх. Я сделала так:
let colorViews: [UIView] = [firstColor, secondColor, thirdColor, forthColor]
        colorViews.forEach { color in
             color.layer.borderWidth = 1.5
             color.layer.borderColor = UIColor.black.cgColor
        }

2024-04-02 20:31 UTC, alexnikxx commented on Notes/ViewController2.swift
> +        let newXPosition = checkbox.frame.origin.x + 36
Зачем тогда вообще эти переменные, если можно написать так?

`checkbox.frame = CGRect(x: 36, y: 4, width: 28, height: 28)`

2024-04-05 11:32 UTC, yukim17 commented on Notes/ViewController2.swift
> +
На больших проектах такие штуки обычно отлавливаются свифт линтом и он тебе подсвечивает где ты что не так сделала, но у нас нет такого, поэтому самой следить только.
Либо можешь попробовать добавить линтер и поразбираться еще с кокоаподсами :)

2024-04-05 11:35 UTC, yukim17 commented on Notes/ViewController2.swift
> +        let newXPosition = checkbox.frame.origin.x + 36
В целом, да. А ты проверяла после исправлений, что все ок работает в разных ориентациях?

2024-04-05 11:39 UTC, yukim17 commented on Notes/CheckboxView.swift
> +    var shapeSize: CGSize = CGSize(width: 28, height: 28)
А вот эта почему не приватная?
И раз уж ты их не меняешь в коде вообще нигде, мб стоит их константами сделать?

2024-04-05 11:39 UTC, yukim17 commented on Notes/CheckboxView.swift
> +    var shapeSize: CGSize = CGSize(width: 28, height: 28)
Везде помни про правило максимальных ограничений - пиши сразу везде лет и прайват, потом если тебе надо будет где-то поменять, то поменяешь(тебе икскод об этом любезно скажет)

2024-04-06 17:25 UTC, alexnikxx commented on Notes/ViewController2.swift
> +        let newXPosition = checkbox.frame.origin.x + 36
да, все ок

2024-04-18 18:31 UTC, yukim17 commented on Notes/CheckboxView.swift
>      private func getCheckboxPath(in rect: CGRect) -> UIBezierPath {
У меня вопрос небольшой - зачем нужен rect, если ты в функции его не используешь вообще никак?

2024-04-30 00:47 UTC, merged